// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pitrd/v1/pitrd.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Volume        string                 `protobuf:"bytes,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Retention     string                 `protobuf:"bytes,3,opt,name=retention,proto3" json:"retention,omitempty"`
	StorageArgs   []string               `protobuf:"bytes,4,rep,name=storage_args,json=storageArgs,proto3" json:"storage_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InitRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *InitRequest) GetRetention() string {
	if x != nil {
		return x.Retention
	}
	return ""
}

func (x *InitRequest) GetStorageArgs() []string {
	if x != nil {
		return x.StorageArgs
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        *VolumeStatus          `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetVolume() *VolumeStatus {
	if x != nil {
		return x.Volume
	}
	return nil
}

type MountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Volume        string                 `protobuf:"bytes,2,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountRequest) Reset() {
	*x = MountRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountRequest) ProtoMessage() {}

func (x *MountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountRequest.ProtoReflect.Descriptor instead.
func (*MountRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{2}
}

func (x *MountRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MountRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

type MountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        *VolumeStatus          `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountResponse) Reset() {
	*x = MountResponse{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountResponse) ProtoMessage() {}

func (x *MountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountResponse.ProtoReflect.Descriptor instead.
func (*MountResponse) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{3}
}

func (x *MountResponse) GetVolume() *VolumeStatus {
	if x != nil {
		return x.Volume
	}
	return nil
}

type UmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UmountRequest) Reset() {
	*x = UmountRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UmountRequest) ProtoMessage() {}

func (x *UmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UmountRequest.ProtoReflect.Descriptor instead.
func (*UmountRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{4}
}

func (x *UmountRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{5}
}

type VolumeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	JfsMount      string                 `protobuf:"bytes,2,opt,name=jfs_mount,json=jfsMount,proto3" json:"jfs_mount,omitempty"`
	FuseMount     string                 `protobuf:"bytes,3,opt,name=fuse_mount,json=fuseMount,proto3" json:"fuse_mount,omitempty"`
	JfsMounted    bool                   `protobuf:"varint,4,opt,name=jfs_mounted,json=jfsMounted,proto3" json:"jfs_mounted,omitempty"`
	FuseMounted   bool                   `protobuf:"varint,5,opt,name=fuse_mounted,json=fuseMounted,proto3" json:"fuse_mounted,omitempty"`
	Retention     string                 `protobuf:"bytes,6,opt,name=retention,proto3" json:"retention,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	HistoryLimit  int32                  `protobuf:"varint,8,opt,name=history_limit,json=historyLimit,proto3" json:"history_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeStatus) Reset() {
	*x = VolumeStatus{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeStatus) ProtoMessage() {}

func (x *VolumeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeStatus.ProtoReflect.Descriptor instead.
func (*VolumeStatus) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{6}
}

func (x *VolumeStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeStatus) GetJfsMount() string {
	if x != nil {
		return x.JfsMount
	}
	return ""
}

func (x *VolumeStatus) GetFuseMount() string {
	if x != nil {
		return x.FuseMount
	}
	return ""
}

func (x *VolumeStatus) GetJfsMounted() bool {
	if x != nil {
		return x.JfsMounted
	}
	return false
}

func (x *VolumeStatus) GetFuseMounted() bool {
	if x != nil {
		return x.FuseMounted
	}
	return false
}

func (x *VolumeStatus) GetRetention() string {
	if x != nil {
		return x.Retention
	}
	return ""
}

func (x *VolumeStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *VolumeStatus) GetHistoryLimit() int32 {
	if x != nil {
		return x.HistoryLimit
	}
	return 0
}

type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DaemonVersion   string                 `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	PostgresHealthy bool                   `protobuf:"varint,2,opt,name=postgres_healthy,json=postgresHealthy,proto3" json:"postgres_healthy,omitempty"`
	Volumes         []*VolumeStatus        `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	// Deprecated: Marked as deprecated in pitrd/v1/pitrd.proto.
	ActiveTransactions int64 `protobuf:"varint,4,opt,name=active_transactions,json=activeTransactions,proto3" json:"active_transactions,omitempty"`
	OpenWrites         int64 `protobuf:"varint,5,opt,name=open_writes,json=openWrites,proto3" json:"open_writes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *StatusResponse) GetPostgresHealthy() bool {
	if x != nil {
		return x.PostgresHealthy
	}
	return false
}

func (x *StatusResponse) GetVolumes() []*VolumeStatus {
	if x != nil {
		return x.Volumes
	}
	return nil
}

// Deprecated: Marked as deprecated in pitrd/v1/pitrd.proto.
func (x *StatusResponse) GetActiveTransactions() int64 {
	if x != nil {
		return x.ActiveTransactions
	}
	return 0
}

func (x *StatusResponse) GetOpenWrites() int64 {
	if x != nil {
		return x.OpenWrites
	}
	return 0
}

type Transaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TxnId          int64                  `protobuf:"varint,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	VersionHash    string                 `protobuf:"bytes,2,opt,name=version_hash,json=versionHash,proto3" json:"version_hash,omitempty"`
	ParentId       *int64                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	ScopePath      string                 `protobuf:"bytes,4,opt,name=scope_path,json=scopePath,proto3" json:"scope_path,omitempty"`
	State          string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Command        string                 `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`
	Message        string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClosedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	PosixOperation string                 `protobuf:"bytes,10,opt,name=posix_operation,json=posixOperation,proto3" json:"posix_operation,omitempty"`
	ProcessCommand string                 `protobuf:"bytes,11,opt,name=process_command,json=processCommand,proto3" json:"process_command,omitempty"`
	ActorUid       int64                  `protobuf:"varint,12,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	ActorGid       int64                  `protobuf:"varint,13,opt,name=actor_gid,json=actorGid,proto3" json:"actor_gid,omitempty"`
	ActorPid       int64                  `protobuf:"varint,14,opt,name=actor_pid,json=actorPid,proto3" json:"actor_pid,omitempty"`
	ActorName      string                 `protobuf:"bytes,15,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ChangeSummary  string                 `protobuf:"bytes,16,opt,name=change_summary,json=changeSummary,proto3" json:"change_summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{8}
}

func (x *Transaction) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *Transaction) GetVersionHash() string {
	if x != nil {
		return x.VersionHash
	}
	return ""
}

func (x *Transaction) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *Transaction) GetScopePath() string {
	if x != nil {
		return x.ScopePath
	}
	return ""
}

func (x *Transaction) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Transaction) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Transaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *Transaction) GetPosixOperation() string {
	if x != nil {
		return x.PosixOperation
	}
	return ""
}

func (x *Transaction) GetProcessCommand() string {
	if x != nil {
		return x.ProcessCommand
	}
	return ""
}

func (x *Transaction) GetActorUid() int64 {
	if x != nil {
		return x.ActorUid
	}
	return 0
}

func (x *Transaction) GetActorGid() int64 {
	if x != nil {
		return x.ActorGid
	}
	return 0
}

func (x *Transaction) GetActorPid() int64 {
	if x != nil {
		return x.ActorPid
	}
	return 0
}

func (x *Transaction) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *Transaction) GetChangeSummary() string {
	if x != nil {
		return x.ChangeSummary
	}
	return ""
}

type BeginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRequest) Reset() {
	*x = BeginRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRequest) ProtoMessage() {}

func (x *BeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRequest.ProtoReflect.Descriptor instead.
func (*BeginRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{9}
}

func (x *BeginRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BeginRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BeginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionHash   string                 `protobuf:"bytes,1,opt,name=version_hash,json=versionHash,proto3" json:"version_hash,omitempty"`
	TxnId         int64                  `protobuf:"varint,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginResponse) Reset() {
	*x = BeginResponse{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginResponse) ProtoMessage() {}

func (x *BeginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginResponse.ProtoReflect.Descriptor instead.
func (*BeginResponse) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{10}
}

func (x *BeginResponse) GetVersionHash() string {
	if x != nil {
		return x.VersionHash
	}
	return ""
}

func (x *BeginResponse) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *BeginResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TxnId         int64                  `protobuf:"varint,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{11}
}

func (x *CommitRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CommitRequest) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *CommitRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionHash   string                 `protobuf:"bytes,1,opt,name=version_hash,json=versionHash,proto3" json:"version_hash,omitempty"`
	TxnId         int64                  `protobuf:"varint,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{12}
}

func (x *CommitResponse) GetVersionHash() string {
	if x != nil {
		return x.VersionHash
	}
	return ""
}

func (x *CommitResponse) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *CommitResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TxnId         int64                  `protobuf:"varint,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{13}
}

func (x *RollbackRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RollbackRequest) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionHash   string                 `protobuf:"bytes,1,opt,name=version_hash,json=versionHash,proto3" json:"version_hash,omitempty"`
	TxnId         int64                  `protobuf:"varint,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{14}
}

func (x *RollbackResponse) GetVersionHash() string {
	if x != nil {
		return x.VersionHash
	}
	return ""
}

func (x *RollbackResponse) GetTxnId() int64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *RollbackResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{15}
}

func (x *LogsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionHash   string                 `protobuf:"bytes,1,opt,name=version_hash,json=versionHash,proto3" json:"version_hash,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,6,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{16}
}

func (x *LogEntry) GetVersionHash() string {
	if x != nil {
		return x.VersionHash
	}
	return ""
}

func (x *LogEntry) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *LogEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LogEntry) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{17}
}

func (x *LogsResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RevertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionHash   string                 `protobuf:"bytes,1,opt,name=version_hash,json=versionHash,proto3" json:"version_hash,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	DryRun        bool                   `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	TargetTime    string                 `protobuf:"bytes,4,opt,name=target_time,json=targetTime,proto3" json:"target_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertRequest) Reset() {
	*x = RevertRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertRequest) ProtoMessage() {}

func (x *RevertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertRequest.ProtoReflect.Descriptor instead.
func (*RevertRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{18}
}

func (x *RevertRequest) GetVersionHash() string {
	if x != nil {
		return x.VersionHash
	}
	return ""
}

func (x *RevertRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RevertRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *RevertRequest) GetTargetTime() string {
	if x != nil {
		return x.TargetTime
	}
	return ""
}

type RevertResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Applied             int64                  `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	NewVersionHash      string                 `protobuf:"bytes,2,opt,name=new_version_hash,json=newVersionHash,proto3" json:"new_version_hash,omitempty"`
	ResolvedVersionHash string                 `protobuf:"bytes,3,opt,name=resolved_version_hash,json=resolvedVersionHash,proto3" json:"resolved_version_hash,omitempty"`
	ResolvedVersionTime string                 `protobuf:"bytes,4,opt,name=resolved_version_time,json=resolvedVersionTime,proto3" json:"resolved_version_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RevertResponse) Reset() {
	*x = RevertResponse{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertResponse) ProtoMessage() {}

func (x *RevertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertResponse.ProtoReflect.Descriptor instead.
func (*RevertResponse) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{19}
}

func (x *RevertResponse) GetApplied() int64 {
	if x != nil {
		return x.Applied
	}
	return 0
}

func (x *RevertResponse) GetNewVersionHash() string {
	if x != nil {
		return x.NewVersionHash
	}
	return ""
}

func (x *RevertResponse) GetResolvedVersionHash() string {
	if x != nil {
		return x.ResolvedVersionHash
	}
	return ""
}

func (x *RevertResponse) GetResolvedVersionTime() string {
	if x != nil {
		return x.ResolvedVersionTime
	}
	return ""
}

type DiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionA      string                 `protobuf:"bytes,1,opt,name=version_a,json=versionA,proto3" json:"version_a,omitempty"`
	VersionB      string                 `protobuf:"bytes,2,opt,name=version_b,json=versionB,proto3" json:"version_b,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffRequest) Reset() {
	*x = DiffRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest) ProtoMessage() {}

func (x *DiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffRequest.ProtoReflect.Descriptor instead.
func (*DiffRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{20}
}

func (x *DiffRequest) GetVersionA() string {
	if x != nil {
		return x.VersionA
	}
	return ""
}

func (x *DiffRequest) GetVersionB() string {
	if x != nil {
		return x.VersionB
	}
	return ""
}

func (x *DiffRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeChanges   int64                  `protobuf:"varint,1,opt,name=node_changes,json=nodeChanges,proto3" json:"node_changes,omitempty"`
	EdgeChanges   int64                  `protobuf:"varint,2,opt,name=edge_changes,json=edgeChanges,proto3" json:"edge_changes,omitempty"`
	ChunkChanges  int64                  `protobuf:"varint,3,opt,name=chunk_changes,json=chunkChanges,proto3" json:"chunk_changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffResponse) Reset() {
	*x = DiffResponse{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse) ProtoMessage() {}

func (x *DiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffResponse.ProtoReflect.Descriptor instead.
func (*DiffResponse) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{21}
}

func (x *DiffResponse) GetNodeChanges() int64 {
	if x != nil {
		return x.NodeChanges
	}
	return 0
}

func (x *DiffResponse) GetEdgeChanges() int64 {
	if x != nil {
		return x.EdgeChanges
	}
	return 0
}

func (x *DiffResponse) GetChunkChanges() int64 {
	if x != nil {
		return x.ChunkChanges
	}
	return 0
}

type RecoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverRequest) Reset() {
	*x = RecoverRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverRequest) ProtoMessage() {}

func (x *RecoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverRequest.ProtoReflect.Descriptor instead.
func (*RecoverRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{22}
}

func (x *RecoverRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RecoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*VolumeStatus        `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverResponse) Reset() {
	*x = RecoverResponse{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverResponse) ProtoMessage() {}

func (x *RecoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverResponse.ProtoReflect.Descriptor instead.
func (*RecoverResponse) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{23}
}

func (x *RecoverResponse) GetVolumes() []*VolumeStatus {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type ConfigSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Window        string                 `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSetRequest) Reset() {
	*x = ConfigSetRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSetRequest) ProtoMessage() {}

func (x *ConfigSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSetRequest.ProtoReflect.Descriptor instead.
func (*ConfigSetRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{24}
}

func (x *ConfigSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigSetRequest) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

type ConfigSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Window        string                 `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSetResponse) Reset() {
	*x = ConfigSetResponse{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSetResponse) ProtoMessage() {}

func (x *ConfigSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSetResponse.ProtoReflect.Descriptor instead.
func (*ConfigSetResponse) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{25}
}

func (x *ConfigSetResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigSetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigSetResponse) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

type ClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Global        bool                   `protobuf:"varint,2,opt,name=global,proto3" json:"global,omitempty"`
	Confirm       bool                   `protobuf:"varint,3,opt,name=confirm,proto3" json:"confirm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRequest.ProtoReflect.Descriptor instead.
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{26}
}

func (x *ClearRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ClearRequest) GetGlobal() bool {
	if x != nil {
		return x.Global
	}
	return false
}

func (x *ClearRequest) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

type ClearResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VersionsDeleted int64                  `protobuf:"varint,1,opt,name=versions_deleted,json=versionsDeleted,proto3" json:"versions_deleted,omitempty"`
	HistoryDeleted  int64                  `protobuf:"varint,2,opt,name=history_deleted,json=historyDeleted,proto3" json:"history_deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClearResponse) Reset() {
	*x = ClearResponse{}
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResponse) ProtoMessage() {}

func (x *ClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pitrd_v1_pitrd_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResponse.ProtoReflect.Descriptor instead.
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return file_pitrd_v1_pitrd_proto_rawDescGZIP(), []int{27}
}

func (x *ClearResponse) GetVersionsDeleted() int64 {
	if x != nil {
		return x.VersionsDeleted
	}
	return 0
}

func (x *ClearResponse) GetHistoryDeleted() int64 {
	if x != nil {
		return x.HistoryDeleted
	}
	return 0
}

var File_pitrd_v1_pitrd_proto protoreflect.FileDescriptor

const file_pitrd_v1_pitrd_proto_rawDesc = "" +
	"\n" +
	"\x14pitrd/v1/pitrd.proto\x12\bpitrd.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n" +
	"\vInitRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\tR\x06volume\x12\x1c\n" +
	"\tretention\x18\x03 \x01(\tR\tretention\x12!\n" +
	"\fstorage_args\x18\x04 \x03(\tR\vstorageArgs\">\n" +
	"\fInitResponse\x12.\n" +
	"\x06volume\x18\x01 \x01(\v2\x16.pitrd.v1.VolumeStatusR\x06volume\":\n" +
	"\fMountRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\tR\x06volume\"?\n" +
	"\rMountResponse\x12.\n" +
	"\x06volume\x18\x01 \x01(\v2\x16.pitrd.v1.VolumeStatusR\x06volume\"#\n" +
	"\rUmountRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x0f\n" +
	"\rStatusRequest\"\xfb\x01\n" +
	"\fVolumeStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tjfs_mount\x18\x02 \x01(\tR\bjfsMount\x12\x1d\n" +
	"\n" +
	"fuse_mount\x18\x03 \x01(\tR\tfuseMount\x12\x1f\n" +
	"\vjfs_mounted\x18\x04 \x01(\bR\n" +
	"jfsMounted\x12!\n" +
	"\ffuse_mounted\x18\x05 \x01(\bR\vfuseMounted\x12\x1c\n" +
	"\tretention\x18\x06 \x01(\tR\tretention\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12#\n" +
	"\rhistory_limit\x18\b \x01(\x05R\fhistoryLimit\"\xea\x01\n" +
	"\x0eStatusResponse\x12%\n" +
	"\x0edaemon_version\x18\x01 \x01(\tR\rdaemonVersion\x12)\n" +
	"\x10postgres_healthy\x18\x02 \x01(\bR\x0fpostgresHealthy\x120\n" +
	"\avolumes\x18\x03 \x03(\v2\x16.pitrd.v1.VolumeStatusR\avolumes\x123\n" +
	"\x13active_transactions\x18\x04 \x01(\x03B\x02\x18\x01R\x12activeTransactions\x12\x1f\n" +
	"\vopen_writes\x18\x05 \x01(\x03R\n" +
	"openWrites\"\xc3\x04\n" +
	"\vTransaction\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\x03R\x05txnId\x12!\n" +
	"\fversion_hash\x18\x02 \x01(\tR\vversionHash\x12 \n" +
	"\tparent_id\x18\x03 \x01(\x03H\x00R\bparentId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"scope_path\x18\x04 \x01(\tR\tscopePath\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x18\n" +
	"\acommand\x18\x06 \x01(\tR\acommand\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tclosed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x12'\n" +
	"\x0fposix_operation\x18\n" +
	" \x01(\tR\x0eposixOperation\x12'\n" +
	"\x0fprocess_command\x18\v \x01(\tR\x0eprocessCommand\x12\x1b\n" +
	"\tactor_uid\x18\f \x01(\x03R\bactorUid\x12\x1b\n" +
	"\tactor_gid\x18\r \x01(\x03R\bactorGid\x12\x1b\n" +
	"\tactor_pid\x18\x0e \x01(\x03R\bactorPid\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x0f \x01(\tR\tactorName\x12%\n" +
	"\x0echange_summary\x18\x10 \x01(\tR\rchangeSummaryB\f\n" +
	"\n" +
	"_parent_id\"<\n" +
	"\fBeginRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x82\x01\n" +
	"\rBeginResponse\x12!\n" +
	"\fversion_hash\x18\x01 \x01(\tR\vversionHash\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\x03R\x05txnId\x127\n" +
	"\vtransaction\x18\x03 \x01(\v2\x15.pitrd.v1.TransactionR\vtransaction\"T\n" +
	"\rCommitRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\x03R\x05txnId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x83\x01\n" +
	"\x0eCommitResponse\x12!\n" +
	"\fversion_hash\x18\x01 \x01(\tR\vversionHash\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\x03R\x05txnId\x127\n" +
	"\vtransaction\x18\x03 \x01(\v2\x15.pitrd.v1.TransactionR\vtransaction\"<\n" +
	"\x0fRollbackRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\x03R\x05txnId\"\x85\x01\n" +
	"\x10RollbackResponse\x12!\n" +
	"\fversion_hash\x18\x01 \x01(\tR\vversionHash\x12\x15\n" +
	"\x06txn_id\x18\x02 \x01(\x03R\x05txnId\x127\n" +
	"\vtransaction\x18\x03 \x01(\v2\x15.pitrd.v1.TransactionR\vtransaction\"7\n" +
	"\vLogsRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xcf\x01\n" +
	"\bLogEntry\x12!\n" +
	"\fversion_hash\x18\x01 \x01(\tR\vversionHash\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x127\n" +
	"\vtransaction\x18\x06 \x01(\v2\x15.pitrd.v1.TransactionR\vtransaction\"<\n" +
	"\fLogsResponse\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.pitrd.v1.LogEntryR\aentries\"\x80\x01\n" +
	"\rRevertRequest\x12!\n" +
	"\fversion_hash\x18\x01 \x01(\tR\vversionHash\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\x12\x1f\n" +
	"\vtarget_time\x18\x04 \x01(\tR\n" +
	"targetTime\"\xbc\x01\n" +
	"\x0eRevertResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\x03R\aapplied\x12(\n" +
	"\x10new_version_hash\x18\x02 \x01(\tR\x0enewVersionHash\x122\n" +
	"\x15resolved_version_hash\x18\x03 \x01(\tR\x13resolvedVersionHash\x122\n" +
	"\x15resolved_version_time\x18\x04 \x01(\tR\x13resolvedVersionTime\"[\n" +
	"\vDiffRequest\x12\x1b\n" +
	"\tversion_a\x18\x01 \x01(\tR\bversionA\x12\x1b\n" +
	"\tversion_b\x18\x02 \x01(\tR\bversionB\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"y\n" +
	"\fDiffResponse\x12!\n" +
	"\fnode_changes\x18\x01 \x01(\x03R\vnodeChanges\x12!\n" +
	"\fedge_changes\x18\x02 \x01(\x03R\vedgeChanges\x12#\n" +
	"\rchunk_changes\x18\x03 \x01(\x03R\fchunkChanges\"$\n" +
	"\x0eRecoverRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"C\n" +
	"\x0fRecoverResponse\x120\n" +
	"\avolumes\x18\x01 \x03(\v2\x16.pitrd.v1.VolumeStatusR\avolumes\"R\n" +
	"\x10ConfigSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06window\x18\x03 \x01(\tR\x06window\"S\n" +
	"\x11ConfigSetResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06window\x18\x03 \x01(\tR\x06window\"T\n" +
	"\fClearRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06global\x18\x02 \x01(\bR\x06global\x12\x18\n" +
	"\aconfirm\x18\x03 \x01(\bR\aconfirm\"c\n" +
	"\rClearResponse\x12)\n" +
	"\x10versions_deleted\x18\x01 \x01(\x03R\x0fversionsDeleted\x12'\n" +
	"\x0fhistory_deleted\x18\x02 \x01(\x03R\x0ehistoryDeleted2\x95\x06\n" +
	"\x05Pitrd\x125\n" +
	"\x04Init\x12\x15.pitrd.v1.InitRequest\x1a\x16.pitrd.v1.InitResponse\x128\n" +
	"\x05Mount\x12\x16.pitrd.v1.MountRequest\x1a\x17.pitrd.v1.MountResponse\x129\n" +
	"\x06Umount\x12\x17.pitrd.v1.UmountRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x06Status\x12\x17.pitrd.v1.StatusRequest\x1a\x18.pitrd.v1.StatusResponse\x128\n" +
	"\x05Begin\x12\x16.pitrd.v1.BeginRequest\x1a\x17.pitrd.v1.BeginResponse\x12;\n" +
	"\x06Commit\x12\x17.pitrd.v1.CommitRequest\x1a\x18.pitrd.v1.CommitResponse\x12A\n" +
	"\bRollback\x12\x19.pitrd.v1.RollbackRequest\x1a\x1a.pitrd.v1.RollbackResponse\x125\n" +
	"\x04Logs\x12\x15.pitrd.v1.LogsRequest\x1a\x16.pitrd.v1.LogsResponse\x12;\n" +
	"\x06Revert\x12\x17.pitrd.v1.RevertRequest\x1a\x18.pitrd.v1.RevertResponse\x125\n" +
	"\x04Diff\x12\x15.pitrd.v1.DiffRequest\x1a\x16.pitrd.v1.DiffResponse\x12>\n" +
	"\aRecover\x12\x18.pitrd.v1.RecoverRequest\x1a\x19.pitrd.v1.RecoverResponse\x12D\n" +
	"\tConfigSet\x12\x1a.pitrd.v1.ConfigSetRequest\x1a\x1b.pitrd.v1.ConfigSetResponse\x128\n" +
	"\x05Clear\x12\x16.pitrd.v1.ClearRequest\x1a\x17.pitrd.v1.ClearResponseB\x19Z\x17pitr_fs/api/pitrd/v1;v1b\x06proto3"

var (
	file_pitrd_v1_pitrd_proto_rawDescOnce sync.Once
	file_pitrd_v1_pitrd_proto_rawDescData []byte
)

func file_pitrd_v1_pitrd_proto_rawDescGZIP() []byte {
	file_pitrd_v1_pitrd_proto_rawDescOnce.Do(func() {
		file_pitrd_v1_pitrd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pitrd_v1_pitrd_proto_rawDesc), len(file_pitrd_v1_pitrd_proto_rawDesc)))
	})
	return file_pitrd_v1_pitrd_proto_rawDescData
}

var file_pitrd_v1_pitrd_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_pitrd_v1_pitrd_proto_goTypes = []any{
	(*InitRequest)(nil),           // 0: pitrd.v1.InitRequest
	(*InitResponse)(nil),          // 1: pitrd.v1.InitResponse
	(*MountRequest)(nil),          // 2: pitrd.v1.MountRequest
	(*MountResponse)(nil),         // 3: pitrd.v1.MountResponse
	(*UmountRequest)(nil),         // 4: pitrd.v1.UmountRequest
	(*StatusRequest)(nil),         // 5: pitrd.v1.StatusRequest
	(*VolumeStatus)(nil),          // 6: pitrd.v1.VolumeStatus
	(*StatusResponse)(nil),        // 7: pitrd.v1.StatusResponse
	(*Transaction)(nil),           // 8: pitrd.v1.Transaction
	(*BeginRequest)(nil),          // 9: pitrd.v1.BeginRequest
	(*BeginResponse)(nil),         // 10: pitrd.v1.BeginResponse
	(*CommitRequest)(nil),         // 11: pitrd.v1.CommitRequest
	(*CommitResponse)(nil),        // 12: pitrd.v1.CommitResponse
	(*RollbackRequest)(nil),       // 13: pitrd.v1.RollbackRequest
	(*RollbackResponse)(nil),      // 14: pitrd.v1.RollbackResponse
	(*LogsRequest)(nil),           // 15: pitrd.v1.LogsRequest
	(*LogEntry)(nil),              // 16: pitrd.v1.LogEntry
	(*LogsResponse)(nil),          // 17: pitrd.v1.LogsResponse
	(*RevertRequest)(nil),         // 18: pitrd.v1.RevertRequest
	(*RevertResponse)(nil),        // 19: pitrd.v1.RevertResponse
	(*DiffRequest)(nil),           // 20: pitrd.v1.DiffRequest
	(*DiffResponse)(nil),          // 21: pitrd.v1.DiffResponse
	(*RecoverRequest)(nil),        // 22: pitrd.v1.RecoverRequest
	(*RecoverResponse)(nil),       // 23: pitrd.v1.RecoverResponse
	(*ConfigSetRequest)(nil),      // 24: pitrd.v1.ConfigSetRequest
	(*ConfigSetResponse)(nil),     // 25: pitrd.v1.ConfigSetResponse
	(*ClearRequest)(nil),          // 26: pitrd.v1.ClearRequest
	(*ClearResponse)(nil),         // 27: pitrd.v1.ClearResponse
	(*timestamppb.Timestamp)(nil), // 28: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 29: google.protobuf.Empty
}
var file_pitrd_v1_pitrd_proto_depIdxs = []int32{
	6,  // 0: pitrd.v1.InitResponse.volume:type_name -> pitrd.v1.VolumeStatus
	6,  // 1: pitrd.v1.MountResponse.volume:type_name -> pitrd.v1.VolumeStatus
	6,  // 2: pitrd.v1.StatusResponse.volumes:type_name -> pitrd.v1.VolumeStatus
	28, // 3: pitrd.v1.Transaction.created_at:type_name -> google.protobuf.Timestamp
	28, // 4: pitrd.v1.Transaction.closed_at:type_name -> google.protobuf.Timestamp
	8,  // 5: pitrd.v1.BeginResponse.transaction:type_name -> pitrd.v1.Transaction
	8,  // 6: pitrd.v1.CommitResponse.transaction:type_name -> pitrd.v1.Transaction
	8,  // 7: pitrd.v1.RollbackResponse.transaction:type_name -> pitrd.v1.Transaction
	8,  // 8: pitrd.v1.LogEntry.transaction:type_name -> pitrd.v1.Transaction
	16, // 9: pitrd.v1.LogsResponse.entries:type_name -> pitrd.v1.LogEntry
	6,  // 10: pitrd.v1.RecoverResponse.volumes:type_name -> pitrd.v1.VolumeStatus
	0,  // 11: pitrd.v1.Pitrd.Init:input_type -> pitrd.v1.InitRequest
	2,  // 12: pitrd.v1.Pitrd.Mount:input_type -> pitrd.v1.MountRequest
	4,  // 13: pitrd.v1.Pitrd.Umount:input_type -> pitrd.v1.UmountRequest
	5,  // 14: pitrd.v1.Pitrd.Status:input_type -> pitrd.v1.StatusRequest
	9,  // 15: pitrd.v1.Pitrd.Begin:input_type -> pitrd.v1.BeginRequest
	11, // 16: pitrd.v1.Pitrd.Commit:input_type -> pitrd.v1.CommitRequest
	13, // 17: pitrd.v1.Pitrd.Rollback:input_type -> pitrd.v1.RollbackRequest
	15, // 18: pitrd.v1.Pitrd.Logs:input_type -> pitrd.v1.LogsRequest
	18, // 19: pitrd.v1.Pitrd.Revert:input_type -> pitrd.v1.RevertRequest
	20, // 20: pitrd.v1.Pitrd.Diff:input_type -> pitrd.v1.DiffRequest
	22, // 21: pitrd.v1.Pitrd.Recover:input_type -> pitrd.v1.RecoverRequest
	24, // 22: pitrd.v1.Pitrd.ConfigSet:input_type -> pitrd.v1.ConfigSetRequest
	26, // 23: pitrd.v1.Pitrd.Clear:input_type -> pitrd.v1.ClearRequest
	1,  // 24: pitrd.v1.Pitrd.Init:output_type -> pitrd.v1.InitResponse
	3,  // 25: pitrd.v1.Pitrd.Mount:output_type -> pitrd.v1.MountResponse
	29, // 26: pitrd.v1.Pitrd.Umount:output_type -> google.protobuf.Empty
	7,  // 27: pitrd.v1.Pitrd.Status:output_type -> pitrd.v1.StatusResponse
	10, // 28: pitrd.v1.Pitrd.Begin:output_type -> pitrd.v1.BeginResponse
	12, // 29: pitrd.v1.Pitrd.Commit:output_type -> pitrd.v1.CommitResponse
	14, // 30: pitrd.v1.Pitrd.Rollback:output_type -> pitrd.v1.RollbackResponse
	17, // 31: pitrd.v1.Pitrd.Logs:output_type -> pitrd.v1.LogsResponse
	19, // 32: pitrd.v1.Pitrd.Revert:output_type -> pitrd.v1.RevertResponse
	21, // 33: pitrd.v1.Pitrd.Diff:output_type -> pitrd.v1.DiffResponse
	23, // 34: pitrd.v1.Pitrd.Recover:output_type -> pitrd.v1.RecoverResponse
	25, // 35: pitrd.v1.Pitrd.ConfigSet:output_type -> pitrd.v1.ConfigSetResponse
	27, // 36: pitrd.v1.Pitrd.Clear:output_type -> pitrd.v1.ClearResponse
	24, // [24:37] is the sub-list for method output_type
	11, // [11:24] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pitrd_v1_pitrd_proto_init() }
func file_pitrd_v1_pitrd_proto_init() {
	if File_pitrd_v1_pitrd_proto != nil {
		return
	}
	file_pitrd_v1_pitrd_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pitrd_v1_pitrd_proto_rawDesc), len(file_pitrd_v1_pitrd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pitrd_v1_pitrd_proto_goTypes,
		DependencyIndexes: file_pitrd_v1_pitrd_proto_depIdxs,
		MessageInfos:      file_pitrd_v1_pitrd_proto_msgTypes,
	}.Build()
	File_pitrd_v1_pitrd_proto = out.File
	file_pitrd_v1_pitrd_proto_goTypes = nil
	file_pitrd_v1_pitrd_proto_depIdxs = nil
}
