// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: pitrd/v1/pitrd.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Pitrd_Init_FullMethodName      = "/pitrd.v1.Pitrd/Init"
	Pitrd_Mount_FullMethodName     = "/pitrd.v1.Pitrd/Mount"
	Pitrd_Umount_FullMethodName    = "/pitrd.v1.Pitrd/Umount"
	Pitrd_Status_FullMethodName    = "/pitrd.v1.Pitrd/Status"
	Pitrd_Begin_FullMethodName     = "/pitrd.v1.Pitrd/Begin"
	Pitrd_Commit_FullMethodName    = "/pitrd.v1.Pitrd/Commit"
	Pitrd_Rollback_FullMethodName  = "/pitrd.v1.Pitrd/Rollback"
	Pitrd_Logs_FullMethodName      = "/pitrd.v1.Pitrd/Logs"
	Pitrd_Revert_FullMethodName    = "/pitrd.v1.Pitrd/Revert"
	Pitrd_Diff_FullMethodName      = "/pitrd.v1.Pitrd/Diff"
	Pitrd_Recover_FullMethodName   = "/pitrd.v1.Pitrd/Recover"
	Pitrd_ConfigSet_FullMethodName = "/pitrd.v1.Pitrd/ConfigSet"
	Pitrd_Clear_FullMethodName     = "/pitrd.v1.Pitrd/Clear"
	Pitrd_Squash_FullMethodName    = "/pitrd.v1.Pitrd/Squash"
	Pitrd_Space_FullMethodName     = "/pitrd.v1.Pitrd/Space"
)

// PitrdClient is the client API for Pitrd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PitrdClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	Mount(ctx context.Context, in *MountRequest, opts ...grpc.CallOption) (*MountResponse, error)
	Umount(ctx context.Context, in *UmountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Begin(ctx context.Context, in *BeginRequest, opts ...grpc.CallOption) (*BeginResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsResponse, error)
	Revert(ctx context.Context, in *RevertRequest, opts ...grpc.CallOption) (*RevertResponse, error)
	Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error)
	Recover(ctx context.Context, in *RecoverRequest, opts ...grpc.CallOption) (*RecoverResponse, error)
	ConfigSet(ctx context.Context, in *ConfigSetRequest, opts ...grpc.CallOption) (*ConfigSetResponse, error)
	Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error)
	Squash(ctx context.Context, in *SquashRequest, opts ...grpc.CallOption) (*SquashResponse, error)
	Space(ctx context.Context, in *SpaceRequest, opts ...grpc.CallOption) (*SpaceResponse, error)
}

type pitrdClient struct {
	cc grpc.ClientConnInterface
}

func NewPitrdClient(cc grpc.ClientConnInterface) PitrdClient {
	return &pitrdClient{cc}
}

func (c *pitrdClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, Pitrd_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Mount(ctx context.Context, in *MountRequest, opts ...grpc.CallOption) (*MountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountResponse)
	err := c.cc.Invoke(ctx, Pitrd_Mount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Umount(ctx context.Context, in *UmountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Pitrd_Umount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Pitrd_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Begin(ctx context.Context, in *BeginRequest, opts ...grpc.CallOption) (*BeginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginResponse)
	err := c.cc.Invoke(ctx, Pitrd_Begin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, Pitrd_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, Pitrd_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogsResponse)
	err := c.cc.Invoke(ctx, Pitrd_Logs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Revert(ctx context.Context, in *RevertRequest, opts ...grpc.CallOption) (*RevertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevertResponse)
	err := c.cc.Invoke(ctx, Pitrd_Revert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffResponse)
	err := c.cc.Invoke(ctx, Pitrd_Diff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Recover(ctx context.Context, in *RecoverRequest, opts ...grpc.CallOption) (*RecoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverResponse)
	err := c.cc.Invoke(ctx, Pitrd_Recover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) ConfigSet(ctx context.Context, in *ConfigSetRequest, opts ...grpc.CallOption) (*ConfigSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigSetResponse)
	err := c.cc.Invoke(ctx, Pitrd_ConfigSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearResponse)
	err := c.cc.Invoke(ctx, Pitrd_Clear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Squash(ctx context.Context, in *SquashRequest, opts ...grpc.CallOption) (*SquashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SquashResponse)
	err := c.cc.Invoke(ctx, Pitrd_Squash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pitrdClient) Space(ctx context.Context, in *SpaceRequest, opts ...grpc.CallOption) (*SpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpaceResponse)
	err := c.cc.Invoke(ctx, Pitrd_Space_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PitrdServer is the server API for Pitrd service.
// All implementations must embed UnimplementedPitrdServer
// for forward compatibility.
type PitrdServer interface {
	Init(context.Context, *InitRequest) (*InitResponse, error)
	Mount(context.Context, *MountRequest) (*MountResponse, error)
	Umount(context.Context, *UmountRequest) (*emptypb.Empty, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Begin(context.Context, *BeginRequest) (*BeginResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	Logs(context.Context, *LogsRequest) (*LogsResponse, error)
	Revert(context.Context, *RevertRequest) (*RevertResponse, error)
	Diff(context.Context, *DiffRequest) (*DiffResponse, error)
	Recover(context.Context, *RecoverRequest) (*RecoverResponse, error)
	ConfigSet(context.Context, *ConfigSetRequest) (*ConfigSetResponse, error)
	Clear(context.Context, *ClearRequest) (*ClearResponse, error)
	Squash(context.Context, *SquashRequest) (*SquashResponse, error)
	Space(context.Context, *SpaceRequest) (*SpaceResponse, error)
	mustEmbedUnimplementedPitrdServer()
}

// UnimplementedPitrdServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPitrdServer struct{}

func (UnimplementedPitrdServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedPitrdServer) Mount(context.Context, *MountRequest) (*MountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mount not implemented")
}
func (UnimplementedPitrdServer) Umount(context.Context, *UmountRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Umount not implemented")
}
func (UnimplementedPitrdServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedPitrdServer) Begin(context.Context, *BeginRequest) (*BeginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Begin not implemented")
}
func (UnimplementedPitrdServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedPitrdServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedPitrdServer) Logs(context.Context, *LogsRequest) (*LogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedPitrdServer) Revert(context.Context, *RevertRequest) (*RevertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Revert not implemented")
}
func (UnimplementedPitrdServer) Diff(context.Context, *DiffRequest) (*DiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Diff not implemented")
}
func (UnimplementedPitrdServer) Recover(context.Context, *RecoverRequest) (*RecoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recover not implemented")
}
func (UnimplementedPitrdServer) ConfigSet(context.Context, *ConfigSetRequest) (*ConfigSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigSet not implemented")
}
func (UnimplementedPitrdServer) Clear(context.Context, *ClearRequest) (*ClearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Clear not implemented")
}
func (UnimplementedPitrdServer) Squash(context.Context, *SquashRequest) (*SquashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Squash not implemented")
}
func (UnimplementedPitrdServer) Space(context.Context, *SpaceRequest) (*SpaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Space not implemented")
}
func (UnimplementedPitrdServer) mustEmbedUnimplementedPitrdServer() {}
func (UnimplementedPitrdServer) testEmbeddedByValue()               {}

// UnsafePitrdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PitrdServer will
// result in compilation errors.
type UnsafePitrdServer interface {
	mustEmbedUnimplementedPitrdServer()
}

func RegisterPitrdServer(s grpc.ServiceRegistrar, srv PitrdServer) {
	// If the following call panics, it indicates UnimplementedPitrdServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pitrd_ServiceDesc, srv)
}

func _Pitrd_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Mount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Mount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Mount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Mount(ctx, req.(*MountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Umount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Umount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Umount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Umount(ctx, req.(*UmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Begin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Begin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Begin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Begin(ctx, req.(*BeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Logs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Logs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Logs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Logs(ctx, req.(*LogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Revert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Revert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Revert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Revert(ctx, req.(*RevertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Diff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Diff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Diff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Diff(ctx, req.(*DiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Recover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Recover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Recover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Recover(ctx, req.(*RecoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_ConfigSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).ConfigSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_ConfigSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).ConfigSet(ctx, req.(*ConfigSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Clear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Clear(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Squash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SquashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Squash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Squash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Squash(ctx, req.(*SquashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pitrd_Space_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PitrdServer).Space(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pitrd_Space_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PitrdServer).Space(ctx, req.(*SpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pitrd_ServiceDesc is the grpc.ServiceDesc for Pitrd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pitrd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pitrd.v1.Pitrd",
	HandlerType: (*PitrdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Pitrd_Init_Handler,
		},
		{
			MethodName: "Mount",
			Handler:    _Pitrd_Mount_Handler,
		},
		{
			MethodName: "Umount",
			Handler:    _Pitrd_Umount_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Pitrd_Status_Handler,
		},
		{
			MethodName: "Begin",
			Handler:    _Pitrd_Begin_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Pitrd_Commit_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _Pitrd_Rollback_Handler,
		},
		{
			MethodName: "Logs",
			Handler:    _Pitrd_Logs_Handler,
		},
		{
			MethodName: "Revert",
			Handler:    _Pitrd_Revert_Handler,
		},
		{
			MethodName: "Diff",
			Handler:    _Pitrd_Diff_Handler,
		},
		{
			MethodName: "Recover",
			Handler:    _Pitrd_Recover_Handler,
		},
		{
			MethodName: "ConfigSet",
			Handler:    _Pitrd_ConfigSet_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _Pitrd_Clear_Handler,
		},
		{
			MethodName: "Squash",
			Handler:    _Pitrd_Squash_Handler,
		},
		{
			MethodName: "Space",
			Handler:    _Pitrd_Space_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pitrd/v1/pitrd.proto",
}
