# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import pitrd_pb2 as pitrd__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pitrd_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PitrdStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/pitrd.v1.Pitrd/Init',
                request_serializer=pitrd__pb2.InitRequest.SerializeToString,
                response_deserializer=pitrd__pb2.InitResponse.FromString,
                _registered_method=True)
        self.Mount = channel.unary_unary(
                '/pitrd.v1.Pitrd/Mount',
                request_serializer=pitrd__pb2.MountRequest.SerializeToString,
                response_deserializer=pitrd__pb2.MountResponse.FromString,
                _registered_method=True)
        self.Umount = channel.unary_unary(
                '/pitrd.v1.Pitrd/Umount',
                request_serializer=pitrd__pb2.UmountRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/pitrd.v1.Pitrd/Status',
                request_serializer=pitrd__pb2.StatusRequest.SerializeToString,
                response_deserializer=pitrd__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Begin = channel.unary_unary(
                '/pitrd.v1.Pitrd/Begin',
                request_serializer=pitrd__pb2.BeginRequest.SerializeToString,
                response_deserializer=pitrd__pb2.BeginResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/pitrd.v1.Pitrd/Commit',
                request_serializer=pitrd__pb2.CommitRequest.SerializeToString,
                response_deserializer=pitrd__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.Rollback = channel.unary_unary(
                '/pitrd.v1.Pitrd/Rollback',
                request_serializer=pitrd__pb2.RollbackRequest.SerializeToString,
                response_deserializer=pitrd__pb2.RollbackResponse.FromString,
                _registered_method=True)
        self.Logs = channel.unary_unary(
                '/pitrd.v1.Pitrd/Logs',
                request_serializer=pitrd__pb2.LogsRequest.SerializeToString,
                response_deserializer=pitrd__pb2.LogsResponse.FromString,
                _registered_method=True)
        self.Revert = channel.unary_unary(
                '/pitrd.v1.Pitrd/Revert',
                request_serializer=pitrd__pb2.RevertRequest.SerializeToString,
                response_deserializer=pitrd__pb2.RevertResponse.FromString,
                _registered_method=True)
        self.Diff = channel.unary_unary(
                '/pitrd.v1.Pitrd/Diff',
                request_serializer=pitrd__pb2.DiffRequest.SerializeToString,
                response_deserializer=pitrd__pb2.DiffResponse.FromString,
                _registered_method=True)
        self.Recover = channel.unary_unary(
                '/pitrd.v1.Pitrd/Recover',
                request_serializer=pitrd__pb2.RecoverRequest.SerializeToString,
                response_deserializer=pitrd__pb2.RecoverResponse.FromString,
                _registered_method=True)
        self.ConfigSet = channel.unary_unary(
                '/pitrd.v1.Pitrd/ConfigSet',
                request_serializer=pitrd__pb2.ConfigSetRequest.SerializeToString,
                response_deserializer=pitrd__pb2.ConfigSetResponse.FromString,
                _registered_method=True)
        self.Clear = channel.unary_unary(
                '/pitrd.v1.Pitrd/Clear',
                request_serializer=pitrd__pb2.ClearRequest.SerializeToString,
                response_deserializer=pitrd__pb2.ClearResponse.FromString,
                _registered_method=True)
        self.Space = channel.unary_unary(
                '/pitrd.v1.Pitrd/Space',
                request_serializer=pitrd__pb2.SpaceRequest.SerializeToString,
                response_deserializer=pitrd__pb2.SpaceResponse.FromString,
                _registered_method=True)


class PitrdServicer:
    """Missing associated documentation comment in .proto file."""

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Umount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Begin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Diff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Space(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PitrdServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=pitrd__pb2.InitRequest.FromString,
                    response_serializer=pitrd__pb2.InitResponse.SerializeToString,
            ),
            'Mount': grpc.unary_unary_rpc_method_handler(
                    servicer.Mount,
                    request_deserializer=pitrd__pb2.MountRequest.FromString,
                    response_serializer=pitrd__pb2.MountResponse.SerializeToString,
            ),
            'Umount': grpc.unary_unary_rpc_method_handler(
                    servicer.Umount,
                    request_deserializer=pitrd__pb2.UmountRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=pitrd__pb2.StatusRequest.FromString,
                    response_serializer=pitrd__pb2.StatusResponse.SerializeToString,
            ),
            'Begin': grpc.unary_unary_rpc_method_handler(
                    servicer.Begin,
                    request_deserializer=pitrd__pb2.BeginRequest.FromString,
                    response_serializer=pitrd__pb2.BeginResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=pitrd__pb2.CommitRequest.FromString,
                    response_serializer=pitrd__pb2.CommitResponse.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=pitrd__pb2.RollbackRequest.FromString,
                    response_serializer=pitrd__pb2.RollbackResponse.SerializeToString,
            ),
            'Logs': grpc.unary_unary_rpc_method_handler(
                    servicer.Logs,
                    request_deserializer=pitrd__pb2.LogsRequest.FromString,
                    response_serializer=pitrd__pb2.LogsResponse.SerializeToString,
            ),
            'Revert': grpc.unary_unary_rpc_method_handler(
                    servicer.Revert,
                    request_deserializer=pitrd__pb2.RevertRequest.FromString,
                    response_serializer=pitrd__pb2.RevertResponse.SerializeToString,
            ),
            'Diff': grpc.unary_unary_rpc_method_handler(
                    servicer.Diff,
                    request_deserializer=pitrd__pb2.DiffRequest.FromString,
                    response_serializer=pitrd__pb2.DiffResponse.SerializeToString,
            ),
            'Recover': grpc.unary_unary_rpc_method_handler(
                    servicer.Recover,
                    request_deserializer=pitrd__pb2.RecoverRequest.FromString,
                    response_serializer=pitrd__pb2.RecoverResponse.SerializeToString,
            ),
            'ConfigSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigSet,
                    request_deserializer=pitrd__pb2.ConfigSetRequest.FromString,
                    response_serializer=pitrd__pb2.ConfigSetResponse.SerializeToString,
            ),
            'Clear': grpc.unary_unary_rpc_method_handler(
                    servicer.Clear,
                    request_deserializer=pitrd__pb2.ClearRequest.FromString,
                    response_serializer=pitrd__pb2.ClearResponse.SerializeToString,
            ),
            'Space': grpc.unary_unary_rpc_method_handler(
                    servicer.Space,
                    request_deserializer=pitrd__pb2.SpaceRequest.FromString,
                    response_serializer=pitrd__pb2.SpaceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pitrd.v1.Pitrd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pitrd.v1.Pitrd', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Pitrd:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Init',
            pitrd__pb2.InitRequest.SerializeToString,
            pitrd__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Mount',
            pitrd__pb2.MountRequest.SerializeToString,
            pitrd__pb2.MountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Umount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Umount',
            pitrd__pb2.UmountRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Status',
            pitrd__pb2.StatusRequest.SerializeToString,
            pitrd__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Begin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Begin',
            pitrd__pb2.BeginRequest.SerializeToString,
            pitrd__pb2.BeginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Commit',
            pitrd__pb2.CommitRequest.SerializeToString,
            pitrd__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Rollback',
            pitrd__pb2.RollbackRequest.SerializeToString,
            pitrd__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Logs',
            pitrd__pb2.LogsRequest.SerializeToString,
            pitrd__pb2.LogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Revert',
            pitrd__pb2.RevertRequest.SerializeToString,
            pitrd__pb2.RevertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Diff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Diff',
            pitrd__pb2.DiffRequest.SerializeToString,
            pitrd__pb2.DiffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Recover',
            pitrd__pb2.RecoverRequest.SerializeToString,
            pitrd__pb2.RecoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/ConfigSet',
            pitrd__pb2.ConfigSetRequest.SerializeToString,
            pitrd__pb2.ConfigSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Clear',
            pitrd__pb2.ClearRequest.SerializeToString,
            pitrd__pb2.ClearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Space(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pitrd.v1.Pitrd/Space',
            pitrd__pb2.SpaceRequest.SerializeToString,
            pitrd__pb2.SpaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
